// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Unf=U9+l7]xhI6{]*^qR":
            case "Enenmy":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . f . . . . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . f f 9 9 f f . . . . 
. . . . . f f 9 9 9 9 f f . . . 
. . . . f f 9 9 9 9 9 9 f f . . 
. . . f f 9 9 9 9 9 9 9 9 f f . 
. . f f 9 9 9 9 9 9 9 9 9 9 f . 
. f f 9 9 9 9 9 9 9 9 9 9 9 f . 
f f f f f f f f f f f f f f f . 
`;
            case "V5#RsaT0|p/?Q4q}=boW":
            case "Trap":return img`
........................
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef...cc.......
.ffffee2222ef.cdc.......
.fe222ffffe2fcddc.......
fffffffeeeffcddc........
ffe44ebf44ecddc.........
fee4d41fddecdc..........
.feee4dddedccc..........
..ffee44e4dde...........
...f222244ee............
...f2222e2f.............
...f444455f.............
....ffffff..............
.....fff................
........................
........................
........................
........................
........................
........................
........................
`;
            case "#F_f`4A:S1o5pT[dqgh*":
            case "bomb":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......fd1111111f.......
......fdd1111111df......
......fddd111111df......
......fdddddd111df......
......fbddddbfd1df......
......fcbbbdcfddbf......
.......fcbb11111f.......
........fffff1b1f.......
........fb111cfbf.......
........ffb1b1ff........
......f.fffbfbf.........
......ffffffff..........
.......fffff............
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
